### PR TITLE
All tests pass

### PR DESCRIPTION
**Pull request by kenpcjr**

### CODE REVIEW

**Comment by markedwardmurray** [comment]
Hey Ken, make sure you're working off your batch repo on `learn-co-students` when you clone your labs, this is the curriculum template ;)

**Comment by kenpcjr** [comment]
Hi Mark,
Thanks for the message. For some reason, the Learn app wasn't able to clone anything when I tried to begin the lab. I also tried the github link on the Learn webpage for the lab but gitHub said no file could be found. That's what lead me to just search for a repo that looked right/close on github. I submitted a bug report for the link error. Sorry for the confusion. Is there something specifically I should search for if I run into this in the future? I tried to search 0616 but didn't don't a similar lab. 

Ken

```
_____________________________
```

**Comment by AnnJohn** [comment]
hi @kenpcjr you should be in the ios-0616 batch. if you go to learn.co/tracks, you'll be able to see all the tracks that you have access to and you can switch to the iOS track from there. thanks!

**Comment by markedwardmurray** [comment]
@AnnJohn looks like that batch repo is a dead end: https://github.com/learn-co-students/objc-dictionary-ice-cream-ios-0616

**Pull request closed without merging**
